package com.example.swd391_be_hiv.model.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class ReportRequest {

    @NotBlank(message = "Generated by is required")
    private String generatedBy;

    @NotBlank(message = "Report type is required")
    private String reportType;

    @NotBlank(message = "Content is required")
    private String content;
}